In [1]:
strx = ""

with open("data.txt","r") as file:
    for line in file:
        strx += line.replace("\n","")
print(strx)

6,6,9,2,1,3,7,4,4,5


In [13]:
sqn = [215, 193, 124, 5, 6, 5, 7, 9, 12,16, 1, 48, 51, 67, 96]




# sqn2Matrix is to convert any sequence to lower triangular matrix, returns matrix as 2x2 array #


import numpy as np                                           # NumPy for some math tools like triangular matrix
import time

def sqn2Matrix(sequence):
    
    dimension = 1 + int(np.ceil(np.sqrt(len(sequence))))

    lowTriMatrix = np.tri(dimension, dimension, 0)
    i = 0

    for row in range(0, dimension, 1):
        for column in range(0, dimension, 1):
            
                if lowTriMatrix[row][column] == 1:
                    lowTriMatrix[row][column] = sqn[i]
                    if i < len(sequence) - 1:
                        i += 1
    return lowTriMatrix, dimension

# primeFinder is to find if a number is prime, returns logical output #

def primeFinder(n):
    
    if n <= 1:
        return False
    if n == 2:
        return True
    if n > 2 and n % 2 == 0:
        return False
    
    halfway_n = int(np.floor(np.sqrt(n)))
    
    for i in range(3, halfway_n + 1, 2):
        if n % i == 0:
            return False
    
    return True

def pathFinder(Matrix):
    
    d = 5
    count = 0
    column = 0
    row = 1
    sum = 0

    while count < d:   
            if primeFinder(Matrix[count][column]) == False:
                sum += np.maximum(Matrix[count][column], Matrix[count][column + 1]) 
            
            if primeFinder(Matrix[count][column]) == True:
                column += 1
                sum += Matrix[count][column]
            count += 1
    return int(sum)




####### definitions are done ########

t0 = time.time()

M, d = sqn2Matrix(sqn)

print(M)

print("Biggest sum is: ", pathFinder(M))

t1 = time.time()
print("Runtime: ", t1 - t0)

[[215.   0.   0.   0.   0.]
 [193. 124.   0.   0.   0.]
 [  5.   6.   5.   0.   0.]
 [  7.   9.  12.  16.   0.]
 [  1.  48.  51.  67.  96.]]
Biggest sum is:  408
Runtime:  0.0009970664978027344
