In [1]:
strx = ""

with open("data.txt","r") as file:
    for line in file:
        strx += line.replace("\n","")
print(strx)

6 6 9 2 1 3 7 4 4 5


In [60]:
#sqn = [215, 193, 124, 5, 6, 5, 7, 9, 12,16, 1, 48, 51, 67, 96, 14, 14, 15, 16, 18, 21]


# sqn2Matrix is to convert any sequence to lower triangular matrix, returns matrix as 2x2 array #


import numpy as np                                           # NumPy for some math tools like triangular matrix
import time

def sqn2Matrix(sequence):
    
    #dimension =  int(np.ceil(np.sqrt(len(sequence))))
    dimension=0
    total=0
    
    while total < len(sequence):
        dimension += 1
        total += dimension
        
    lowTriMatrix = np.tri(dimension, dimension, 0)
    i = 0

    for row in range(0, dimension, 1):
        for column in range(0, dimension, 1):
            
                if lowTriMatrix[row][column] == 1:
                    lowTriMatrix[row][column] = int(sequence[i])
                    if i < len(sequence) - 1:
                        i += 1
    return lowTriMatrix

# primeFinder is to find if a number is prime, returns logical true/false #

def primeFinder(n):
    
    if n <= 1:
        return False
    if n == 2:
        return True
    if n > 2 and n % 2 == 0:
        return False
    
    halfway_n = int(np.floor(np.sqrt(n)))
    
    for i in range(3, halfway_n + 1, 2):
        if n % i == 0:
            return False
    
    return True

def pathFinder(Matrix):
    
    d = len(M)
    count = 0
    column = 0
    row = 1
    sum = 0

    while count < d:   
            if primeFinder(Matrix[count][column]) == False:
                sum += np.maximum(Matrix[count][column], Matrix[count][column + 1]) 
            
            if primeFinder(Matrix[count][column]) == True:
                column += 1
                sum += Matrix[count][column]
            count += 1
    return int(sum)

def read_txt(txtFile):
    
    sqn=[]
    
    with open(txtFile,"r") as infile:
        for line in infile:
            
            line = line.replace("\n","")
            sqn.extend(line.split(" "))
    return sqn

def pathFinder2(matrix):
    
    dimension = len(matrix)
    possible_paths = []
    row = dimension-1
    column=dimension-1
    done=False
    path = []
        
    while not done:
        path.append(matrix[row][column])
        
        while row != 0:
            path.append(matrix[row][column])
            p1 = matrix[row - 1][column]
            
            if column>1:
                p2 = matrix[row-1][column-1]
            
            else:
                p2=0
            
            path.append([p1,p2])
            row -= 1
            column -= 1
        
        possible_paths.append(path)
        column = dimension - 1
        
        if column < 0:
            done = True
    
    return possible_paths

####### definitions are done ########


S = read_txt('data.txt')

t0 = time.time()

M = sqn2Matrix(S)

print(M)
print(len(M))

print("Biggest sum is: ", pathFinder(M))

#print("Possible paths: ", pathFinder2(M))

t1 = time.time()
print("Runtime: ", t1 - t0)

[[ 6.  0.  0.  0.  0.]
 [ 6.  9.  0.  0.  0.]
 [ 2.  1.  3.  0.  0.]
 [ 7.  4.  4.  5.  0.]
 [12. 15. 47. 47. 47.]]
5
Biggest sum is:  67
Runtime:  0.0010979175567626953
